name: "Actual Budget (higher limits)"
description: "Run the latest stable version of Actual Budget. With higher limits!"
url: "https://actualbudget.org"
slug: "actualbudget"
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
startup: application
webui: "[PROTO:option_name]://[HOST]:[PORT:5006]"
boot: auto
ports:
  5006/tcp: 5006
image: ghcr.io/actualbudget/actual-server
version: 25.10.0-alpine
environment:
  ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB: "200"
  ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB: "200"
  ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB: "200"